### ISSUE TITLE
Оформление тестов

### ISSUE THREAD

**Issue by alexmikhalevich** [Karen-1999/BattleOfRaces#9]
Если это заготовка на будущее, то тест проходить не должен. Как раз чтобы сигнализировать о том, что вы это должны сделать. У вас есть два варианта:

1. сделать так, чтобы тест был failed. это нормальный способ, однако вы, возможно, не хотели так делать из-за требований на отсутствие "красных" тестов.
2. сделать тест disabled. https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#temporarily-disabling-tests

https://github.com/Karen-1999/BattleOfRaces/blob/bf01d0d7a4a7ed3f8b465bf2bea8260f4a37ab5f/headers/tests.h#L229

**Comment by DimaProskurin** [comment]
Исправлено
